"""Create nodes and node_closure

Revision ID: 0001_closure_schema
Revises:
Create Date: 2026-08-14

Hand-written rather than autogenerated: the native Postgres enum needs its CREATE TYPE and
DROP TYPE spelled out, which autogenerate does not produce reliably.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_closure_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# create_type=False so the type is created and dropped only where this file says so. Left
# to itself, CREATE TABLE emits its own CREATE TYPE and DROP TABLE leaves the type behind,
# which makes `downgrade base` followed by `upgrade head` fail on "type node_type already
# exists" -- a break that only shows up for whoever resets their database next.
node_type = postgresql.ENUM(
    'management_group',
    'subscription',
    'resource_group',
    name='node_type',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    node_type.create(op.get_bind(), checkfirst=False)

    op.create_table(
        'nodes',
        # autoincrement=False: ids come from the client. Without it a BigInteger primary
        # key compiles to BIGSERIAL, and Postgres would own a sequence that every insert
        # overrides.
        sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('type', node_type, nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'node_closure',
        sa.Column('ancestor_id', sa.BigInteger(), nullable=False),
        sa.Column('descendant_id', sa.BigInteger(), nullable=False),
        sa.Column('depth', sa.Integer(), nullable=False),
        # ON DELETE CASCADE both ways, so deleting a node takes its closure rows with it
        # and the write path never has to clean up behind itself.
        sa.ForeignKeyConstraint(
            ['ancestor_id'], ['nodes.id'],
            name='fk_node_closure_ancestor', ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['descendant_id'], ['nodes.id'],
            name='fk_node_closure_descendant', ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('ancestor_id', 'descendant_id'),
        # >= 0, not > 0: depth 0 is the self-row every node carries, which is what makes
        # "node exists" distinguishable from "node has no descendants".
        sa.CheckConstraint('depth >= 0', name='ck_node_closure_depth_non_negative'),
    )

    # The primary key already indexes (ancestor_id, descendant_id); this covers lookups
    # that start from the descendant, which is how the read path finds a node's parent.
    op.create_index('ix_closure_descendant_depth', 'node_closure', ['descendant_id', 'depth'])

    # At most one depth-1 row per node => at most one parent => the stored graph can only
    # ever be a forest. Postgres enforces it, so no future caller can write around it.
    op.create_index(
        'uq_node_single_parent',
        'node_closure',
        ['descendant_id'],
        unique=True,
        postgresql_where=sa.text('depth = 1'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('uq_node_single_parent', table_name='node_closure')
    op.drop_index('ix_closure_descendant_depth', table_name='node_closure')
    op.drop_table('node_closure')
    op.drop_table('nodes')
    # The type belongs to the schema, not to the table that uses it, so it survives
    # DROP TABLE and has to go explicitly.
    node_type.drop(op.get_bind(), checkfirst=False)
