-- Intentionally empty.
--
-- This file ran only when the data directory was empty, which made it a poor place for
-- a schema: editing it had no effect on a database that already existed. The hierarchy
-- tables are created by Alembic migrations instead, which run on every container start
-- and are versioned alongside the code.
--
-- The `tenants` table that used to live here was the assignment's mock reference table.
-- It was never part of the domain -- no relationship to the hierarchy, and the README
-- describes it as "1 mock table for reference" -- so it has been removed.
